server:
  port: 8082

spring:
  application:
    name: path-service
  datasource:
    url: jdbc:h2:mem:pathdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.aigrowth: DEBUG
